[package]
name = "select-examples"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
tokio = { version = "1.43.0", features = ["full"] }
tracing = "0.1.41"

[dev-dependencies]
tracing-test = "0.2.5"
