# The URL the site will be built for
base_url = "https://barafael.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# ignore readmes, like the readme of the marp-theme-rhea git submodule
ignored_content = ["*/README.md"]

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "apollo"
taxonomies = [{ name = "tags" }]

[markdown.highlighting]
light_theme = "light-plus"
dark_theme = "gruvbox-dark-medium"

[extra]
katex_enable = true

toc = true

theme = "toggle"
repo_url = "https://github.com/barafael/barafael.github.io"

socials = [
    { name = "github", url = "https://github.com/barafael/", icon = "github" },
]
stylesheets = ["custom.css"]

menu = [
    { name = "/posts", url = "/posts", weight = 1 },
    # { name = "/projects", url = "../projects", weight = 2 },
]
