[package]
name = "nice-loop-select"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.96"
futures = "0.3.31"
tokio = { version = "1.43.0", features = ["full"] }
tracing = "0.1.41"

[dev-dependencies]
tracing-test = "0.2.5"
